---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: kube-system
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: home-operations
        namespace: flux-system
  values:
    apiService:
      create: true
    # Required for K3s self-signed certs
    extraArgs:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
