---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system

spec:
  interval: 1h
  type: "oci"
  url: oci://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: kube-system
  chart:
    spec:
      chart: metrics-server
      version: 7.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    apiService:
      create: true
    # Required for K3s self-signed certs
    extraArgs:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
